/**
 * ESPHome font package generator.
 *
 * Produces a ZIP that contains everything a user needs to drop a custom font
 * into an ESPHome project:
 *  - the compiled .ttf file,
 *  - a LICENSE.txt (matching whatever license the font currently carries),
 *  - an esphome/ directory with a ready-to-merge YAML snippet, and
 *  - a README.md explaining how to use the package.
 */
import JSZip from 'jszip';
import type { FontDoc } from '../core/types';
import { buildLicenseTxt } from '../core/license';
import { downloadBlob } from './persistence';
import { exportFont } from './exportService';
import { DEFAULT_EXPORT_OPTIONS } from '../core/fontCodec';
import { makePostScriptName, sanitizePostScriptFragment } from '../core/metadata';

export interface EsphomeExportOptions {
  /** Glyph set YAML string (e.g. "glyphs: !include glyphs.txt" or a literal list). */
  glyphsYaml?: string;
  /** Desired pixel size at which ESPHome will render the font (default 16). */
  fontSize?: number;
  /** Variable name used in the YAML id: field (default: derived from family). */
  idName?: string;
}

/** Produce a safe ESPHome id from the font family/style. */
function safeId(family: string, style: string): string {
  const base = sanitizePostScriptFragment(`${family}_${style}`)
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
  return (base || 'my_font').toLowerCase();
}

/** Collect Unicode code points the font actually has glyphs for (excluding .notdef and unmapped). */
function supportedGlyphs(doc: FontDoc): string {
  const cps: number[] = [];
  for (const g of doc.glyphs) {
    if (g.unicode !== null && g.name !== '.notdef' && (g.pixel || g.contours.length > 0 || g.compound)) {
      cps.push(g.unicode);
    }
  }
  cps.sort((a, b) => a - b);
  return String.fromCodePoint(...cps);
}

/** Escape a string for use inside a YAML double-quoted value. */
function yamlQuote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/** Build the ESPHome YAML snippet. */
function buildYaml(doc: FontDoc, opts: EsphomeExportOptions, ttfFileName: string): string {
  const id = (opts.idName || safeId(doc.meta.fontFamily, doc.meta.fontSubFamily)).slice(0, 40);
  const size = Math.max(1, Math.round(opts.fontSize ?? 16));
  const glyphsLiteral = supportedGlyphs(doc);
  return `# ESPHome font configuration — ${doc.meta.fontFamily} ${doc.meta.fontSubFamily}
# Generated by Pixeel v${__APP_VERSION__} — https://sandro-defender.github.io/Pixeel-font-editor/
#
# Usage:
#   1. Copy the \`esphome/\` folder and the .ttf next to your node's YAML.
#   2. Add "package: includes:" or paste the font: block below into your config.
#   3. Re-flash your device.

font:
  - file: "${ttfFileName}"
    id: ${id}
    size: ${size}
    # Only the glyphs that are defined in your font are listed below, keeping
    # the firmware binary small. Edit this list to add/remove characters.
    glyphs: ${yamlQuote(glyphsLiteral)}
`;
}

/** Build the README for the ESPHome package. */
function buildReadme(doc: FontDoc, opts: EsphomeExportOptions, ttfFileName: string, yamlFileName: string): string {
  const lines: string[] = [];
  lines.push(`# ${doc.meta.fontFamily} ${doc.meta.fontSubFamily} — ESPHome package`);
  lines.push('');
  lines.push(`Generated by **Pixeel** (v${__APP_VERSION__}) — the browser-based TTF font editor.`);
  lines.push('');
  lines.push('## Contents');
  lines.push('');
  lines.push(`- \`${ttfFileName}\` — the compiled TrueType font.`);
  lines.push(`- \`esphome/${yamlFileName}\` — ready-to-paste font block for your ESPHome YAML.`);
  lines.push('- `esphome/glyphs.txt` — the supported glyphs as plain text (for `!include`).');
  lines.push('- `LICENSE.txt` — the font license (respect it when redistributing).');
  lines.push('');
  lines.push('## Quick start');
  lines.push('');
  lines.push('1. Copy the `.ttf` and the `esphome/` folder into your ESPHome project directory (next to your node `.yaml`).');
  lines.push(`2. Either add the font block from \`esphome/${yamlFileName}\` into your config, or use an include:`);
  lines.push('');
  lines.push('   ```yaml');
  lines.push('   font:');
  lines.push(`     - file: "${ttfFileName}"`);
  lines.push(`       id: ${safeId(doc.meta.fontFamily, doc.meta.fontSubFamily)}`);
  lines.push(`       size: ${Math.max(1, Math.round(opts.fontSize ?? 16))}`);
  lines.push('       glyphs: !include esphome/glyphs.txt');
  lines.push('   ```');
  lines.push('');
  lines.push('3. Reference the font from a display lambda, e.g.:');
  lines.push('');
  lines.push('   ```cpp');
  lines.push(`   it.print(0, 0, id(${safeId(doc.meta.fontFamily, doc.meta.fontSubFamily)}), "Hello!");`);
  lines.push('   ```');
  lines.push('');
  lines.push('4. Compile and flash. ESPHome will rasterize only the listed glyphs into the firmware, keeping flash usage small.');
  lines.push('');
  lines.push('## Adjusting');
  lines.push('');
  lines.push('- Edit `size:` in the YAML to render at a different pixel size.');
  lines.push('- Edit the `glyphs:` string (or `glyphs.txt`) to include exactly the characters your project needs.');
  lines.push('- Re-export from Pixeel whenever you modify the font.');
  lines.push('');
  if (doc.meta.designer) lines.push(`**Author:** ${doc.meta.designer}  `);
  if (doc.meta.version) lines.push(`**Font version:** ${doc.meta.version}  `);
  if (doc.meta.urlOfFontDesigner) lines.push(`**Designer URL:** ${doc.meta.urlOfFontDesigner}  `);
  if (doc.meta.licence.trim()) lines.push(`See \`LICENSE.txt\` for the font license.`);
  lines.push('');
  return lines.join('\n');
}

/** Name of the generated ESPHome package archive for a font. */
export function esphomePackageName(doc: FontDoc): string {
  const psName = doc.meta.postScriptName && doc.meta.postScriptName.trim()
    ? doc.meta.postScriptName
    : makePostScriptName(doc.meta.fontFamily, doc.meta.fontSubFamily);
  return `${psName}-esphome.zip`;
}

export interface EsphomePackage {
  /** The .ttf bytes that were embedded in the archive. */
  ttf: ArrayBuffer;
  /** Ready-to-paste ESPHome `font:` block. */
  yaml: string;
  /** Plain-text glyph set (for `!include`). */
  glyphs: string;
  /** The license text shipped alongside the font. */
  license: string;
  readme: string;
  ttfFileName: string;
  yamlFileName: string;
  fileName: string;
  /** The completed ZIP archive. */
  blob: Blob;
}

/**
 * Build everything ESPHome needs: the compiled TTF, a ready-to-paste `font:`
 * block, the glyph list, the license and a short README — bundled in one ZIP.
 * Pure (no download); `exportEsphomePackage` adds the browser download.
 */
export async function buildEsphomePackage(doc: FontDoc, opts: EsphomeExportOptions = {}): Promise<EsphomePackage> {
  const psName = doc.meta.postScriptName && doc.meta.postScriptName.trim()
    ? doc.meta.postScriptName
    : makePostScriptName(doc.meta.fontFamily, doc.meta.fontSubFamily);
  const ttfFileName = `${psName}.ttf`;
  const yamlFileName = `${psName}.yaml`;
  const glyphs = supportedGlyphs(doc);

  const { buffer } = await exportFont(doc, { ...DEFAULT_EXPORT_OPTIONS });
  const license = buildLicenseTxt(doc.meta) || 'All rights reserved.';
  const yaml = buildYaml(doc, opts, ttfFileName);
  const readme = buildReadme(doc, opts, ttfFileName, yamlFileName);

  const zip = new JSZip();
  zip.file(ttfFileName, buffer);
  zip.file('LICENSE.txt', license);
  const espDir = zip.folder('esphome');
  if (espDir) {
    espDir.file(yamlFileName, yaml);
    espDir.file('glyphs.txt', glyphs);
  }
  zip.file('README.md', readme);

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
  return {
    ttf: buffer,
    yaml,
    glyphs,
    license,
    readme,
    ttfFileName,
    yamlFileName,
    fileName: `${psName}-esphome.zip`,
    blob,
  };
}

/**
 * Export a ZIP with everything ESPHome needs: TTF, YAML, glyph list, LICENSE, README.
 * Triggers a browser download.
 */
export async function exportEsphomePackage(doc: FontDoc, opts: EsphomeExportOptions = {}): Promise<{ bytes: number; fileName: string }> {
  const pkg = await buildEsphomePackage(doc, opts);
  downloadBlob(pkg.blob, pkg.fileName);
  return { bytes: pkg.blob.size, fileName: pkg.fileName };
}
